# Copyright (c) 2023 Intercreate, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Authors: J.P. Hutchins <jp@intercreate.io>

name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup GIT
        run: |
          git config --global user.name "Intercreate"
          git config --global user.email ic@n0t4d0m41n.1337
          git tag 0.0.0

      - name: Configure & run tests
        run: cmake -B tests/build -S tests --log-level=NOTICE
